### ISSUE TITLE
New-PWFHeader does not work

### ISSUE THREAD

**Issue by muffpistol** [qschweitzer/Powershell-HTML5-Reporting#2]
I copied your "What to know?" code block directly from Github and used it as the first test of your module and when viewing the output .html file, the error "The term 'New-PWFHeader' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. " is all that the .html file contains.  No errors were thrown in the powershell session.  If I comment out the New-PWFHeader cmdlet in the code and re-run the report, it does create a sample report with cards and whatnot.

**Comment by qschweitzer** [comment]
Hi, sorry for this veeeeery too late reply.
The app don't notify me about your comment...

So it was a syntax issue, I've changed the New-PWFHeader name to New-PWFCardHeader.
I forget to change it in the readme :/

FYI I'm working on a new real documentation for this project.
Thanks.
